server:
  port: 8080
  servlet:
    contextPath: /

#  logging:
#    level:
#      org.springframework.security: INFO
#      org.springframework.web: INFO

#application:
#  secret: SecretKeyToGenJWTs
#  authorization: Authorization
#  bearer: Bearerx
#  access_token: access_token

spring:
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      database: biblio
      host: localhost
      port: 27017
  security:
    user:
      password: test
      name: test