spring:
#  data:
#    mongodb:
#      database: biblio
#      host: localhost
#      port: 27017
  security:
    user:
      password: test
      name: test
  jackson:
    default-property-inclusion: NON_NULL


server:
  servlet:
    contextPath: /biblio